# TCL File Generated by Component Editor 12.0
# Sat Feb 23 19:33:30 GMT 2013
# DO NOT MODIFY


# 
# fp_cust_insn "fp_cust_insn" v1.0
# null 2013.02.23.19:33:30
# 
# 

# 
# request TCL package from ACDS 12.0
# 
package require -exact qsys 12.0


# 
# module fp_cust_insn
# 
set_module_property NAME fp_cust_insn
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property DISPLAY_NAME fp_cust_insn
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL fp_cust_insn
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file fp_cust_insn.v VERILOG PATH fp_custom/fp_cust_insn.v

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL fp_cust_insn
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file fp_cust_insn.v VERILOG PATH fp_custom/fp_cust_insn.v


# 
# parameters
# 
add_parameter fp_add_latency INTEGER 7
set_parameter_property fp_add_latency DEFAULT_VALUE 7
set_parameter_property fp_add_latency DISPLAY_NAME fp_add_latency
set_parameter_property fp_add_latency TYPE INTEGER
set_parameter_property fp_add_latency UNITS None
set_parameter_property fp_add_latency ALLOWED_RANGES -2147483648:2147483647
add_parameter fp_sub_latency INTEGER 7
set_parameter_property fp_sub_latency DEFAULT_VALUE 7
set_parameter_property fp_sub_latency DISPLAY_NAME fp_sub_latency
set_parameter_property fp_sub_latency TYPE INTEGER
set_parameter_property fp_sub_latency UNITS None
set_parameter_property fp_sub_latency ALLOWED_RANGES -2147483648:2147483647
add_parameter fp_mul_latency INTEGER 5
set_parameter_property fp_mul_latency DEFAULT_VALUE 5
set_parameter_property fp_mul_latency DISPLAY_NAME fp_mul_latency
set_parameter_property fp_mul_latency TYPE INTEGER
set_parameter_property fp_mul_latency UNITS None
set_parameter_property fp_mul_latency ALLOWED_RANGES -2147483648:2147483647
add_parameter add_opcode INTEGER 0
set_parameter_property add_opcode DEFAULT_VALUE 0
set_parameter_property add_opcode DISPLAY_NAME add_opcode
set_parameter_property add_opcode TYPE INTEGER
set_parameter_property add_opcode UNITS None
set_parameter_property add_opcode ALLOWED_RANGES -2147483648:2147483647
add_parameter sub_opcode INTEGER 1
set_parameter_property sub_opcode DEFAULT_VALUE 1
set_parameter_property sub_opcode DISPLAY_NAME sub_opcode
set_parameter_property sub_opcode TYPE INTEGER
set_parameter_property sub_opcode UNITS None
set_parameter_property sub_opcode ALLOWED_RANGES -2147483648:2147483647
add_parameter mul_opcode INTEGER 2
set_parameter_property mul_opcode DEFAULT_VALUE 2
set_parameter_property mul_opcode DISPLAY_NAME mul_opcode
set_parameter_property mul_opcode TYPE INTEGER
set_parameter_property mul_opcode UNITS None
set_parameter_property mul_opcode ALLOWED_RANGES -2147483648:2147483647


# 
# display items
# 


# 
# connection point nios_custom_instruction_slave
# 
add_interface nios_custom_instruction_slave nios_custom_instruction end
set_interface_property nios_custom_instruction_slave clockCycle 0
set_interface_property nios_custom_instruction_slave operands 2
set_interface_property nios_custom_instruction_slave ENABLED true

add_interface_port nios_custom_instruction_slave dataa dataa Input 32
add_interface_port nios_custom_instruction_slave datab datab Input 32
add_interface_port nios_custom_instruction_slave result result Output 32
add_interface_port nios_custom_instruction_slave reset reset Input 1
add_interface_port nios_custom_instruction_slave clk clk Input 1
add_interface_port nios_custom_instruction_slave clk_en clk_en Input 1
add_interface_port nios_custom_instruction_slave start start Input 1
add_interface_port nios_custom_instruction_slave done done Output 1
add_interface_port nios_custom_instruction_slave n n Input 2

