add wave -noupdate -divider {first_nios2_system_cpu: top-level ports}
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/i_readdata
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/i_readdatavalid
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/i_waitrequest
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/i_address
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/i_read
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/clk
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/reset_n
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/d_readdata
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/d_waitrequest
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/d_address
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/d_byteenable
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/d_read
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/d_write
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/d_writedata
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/d_irq
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/d_readdatavalid
add wave -noupdate -divider {first_nios2_system_cpu: base pipeline}
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/clk
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/reset_n
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/D_stall
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/A_stall
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/F_pcb_nxt
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/F_pcb
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/D_pcb
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/E_pcb
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/M_pcb
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/A_pcb
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/W_pcb
add wave -noupdate -format Logic -radix ascii /test_bench/DUT/the_first_nios2_system_cpu/F_vinst
add wave -noupdate -format Logic -radix ascii /test_bench/DUT/the_first_nios2_system_cpu/D_vinst
add wave -noupdate -format Logic -radix ascii /test_bench/DUT/the_first_nios2_system_cpu/E_vinst
add wave -noupdate -format Logic -radix ascii /test_bench/DUT/the_first_nios2_system_cpu/M_vinst
add wave -noupdate -format Logic -radix ascii /test_bench/DUT/the_first_nios2_system_cpu/A_vinst
add wave -noupdate -format Logic -radix ascii /test_bench/DUT/the_first_nios2_system_cpu/W_vinst
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/F_inst_ram_hit
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/F_iw_valid
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/F_issue
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/F_kill
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/D_kill
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/D_refetch
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/D_issue
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/D_valid
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/D_rdprs_stall
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/D_rdprs_stall_done
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/E_valid
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/M_valid
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/A_valid
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/W_valid
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/W_wr_dst_reg
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/W_dst_regnum
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/W_wr_data
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/D_en
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/E_en
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/M_en
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/A_en
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/F_iw
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/D_iw
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/E_iw
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/M_pipe_flush
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/M_pipe_flush_baddr
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/norm_intr_req
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/A_status_reg
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/A_status_reg_pie
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/A_estatus_reg
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/A_estatus_reg_pie
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/A_bstatus_reg
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/A_bstatus_reg_pie
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/A_ienable_reg
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/A_ienable_reg_irq1
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/A_ienable_reg_irq16
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/A_ienable_reg_irq20
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/A_ipending_reg
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/A_ipending_reg_irq1
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/A_ipending_reg_irq16
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/A_ipending_reg_irq20
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/A_cpuid_reg
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/E_valid_prior_to_hbreak

configure wave -justifyvalue right
configure wave -signalnamewidth 1
TreeUpdate [SetDefaultTree]
