add wave -noupdate -divider {first_nios2_system_cpu: top-level ports}
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/i_readdata
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/i_readdatavalid
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/i_waitrequest
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/i_address
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/i_read
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/M_ci_multi_dataa
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/M_ci_multi_datab
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/M_ci_multi_ipending
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/M_ci_multi_status
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/M_ci_multi_estatus
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/M_ci_multi_n
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/M_ci_multi_a
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/M_ci_multi_b
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/M_ci_multi_c
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/M_ci_multi_readra
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/M_ci_multi_readrb
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/M_ci_multi_writerc
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/M_ci_multi_result
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/M_ci_multi_clk_en
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/M_ci_multi_start
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/M_ci_multi_done
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/clk
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/reset_n
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/d_readdata
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/d_waitrequest
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/d_irq
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/d_address
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/d_byteenable
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/d_read
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/d_write
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/d_writedata
add wave -noupdate -divider {first_nios2_system_cpu: base pipeline}
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/clk
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/reset_n
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/M_stall
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/F_pcb_nxt
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/F_pcb
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/D_pcb
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/E_pcb
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/M_pcb
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/W_pcb
add wave -noupdate -format Logic -radix ascii /test_bench/DUT/the_first_nios2_system_cpu/F_vinst
add wave -noupdate -format Logic -radix ascii /test_bench/DUT/the_first_nios2_system_cpu/D_vinst
add wave -noupdate -format Logic -radix ascii /test_bench/DUT/the_first_nios2_system_cpu/E_vinst
add wave -noupdate -format Logic -radix ascii /test_bench/DUT/the_first_nios2_system_cpu/M_vinst
add wave -noupdate -format Logic -radix ascii /test_bench/DUT/the_first_nios2_system_cpu/W_vinst
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/F_inst_ram_hit
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/F_iw_valid
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/F_issue
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/F_kill
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/D_kill
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/D_refetch
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/D_issue
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/D_valid
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/E_valid
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/M_valid
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/W_valid
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/W_wr_dst_reg
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/W_dst_regnum
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/W_wr_data
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/F_en
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/D_en
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/E_en
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/M_en
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/F_iw
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/D_iw
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/E_iw
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/E_valid_prior_to_hbreak
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/M_pipe_flush_nxt
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/M_pipe_flush_baddr_nxt
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/M_status_reg_pie
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/M_ienable_reg
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/intr_req
add wave -noupdate -divider {first_nios2_system_cpu: multicycle_custom_instruction}
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/M_ctrl_custom_multi
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/M_ci_multi_dataa
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/M_ci_multi_datab
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/M_ci_multi_ipending
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/M_ci_multi_status
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/M_ci_multi_estatus
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/M_ci_multi_n
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/M_ci_multi_readra
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/M_ci_multi_readrb
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/M_ci_multi_writerc
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/M_ci_multi_result
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/M_ci_multi_clk_en
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/M_ci_multi_start
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/M_ci_multi_done
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_first_nios2_system_cpu/M_ci_multi_stall

configure wave -justifyvalue right
configure wave -signalnamewidth 1
TreeUpdate [SetDefaultTree]
